/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// CreateTunedModelRequest
    /// </summary>
    [DataContract(Name = "CreateTunedModelRequest")]
    public partial class CreateTunedModelRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTunedModelRequest" /> class.
        /// </summary>
        /// <param name="tunedModelId">Optional. The unique id for the tuned model if specified.</param>
        /// <param name="tunedModel">tunedModel.</param>
        public CreateTunedModelRequest(string tunedModelId = default, TunedModel tunedModel = default)
        {
            this.TunedModelId = tunedModelId;
            this.TunedModel = tunedModel;
        }

        /// <summary>
        /// Optional. The unique id for the tuned model if specified
        /// </summary>
        /// <value>Optional. The unique id for the tuned model if specified</value>
        [DataMember(Name = "tunedModelId", EmitDefaultValue = false)]
        public string TunedModelId { get; set; }

        /// <summary>
        /// Gets or Sets TunedModel
        /// </summary>
        [DataMember(Name = "tunedModel", EmitDefaultValue = false)]
        public TunedModel TunedModel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateTunedModelRequest {\n");
            sb.Append("  TunedModelId: ").Append(TunedModelId).Append("\n");
            sb.Append("  TunedModel: ").Append(TunedModel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
