/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// ExecutableCode
    /// </summary>
    [DataContract(Name = "ExecutableCode")]
    public partial class ExecutableCode : IValidatableObject
    {
        /// <summary>
        /// Programming language of the code
        /// </summary>
        /// <value>Programming language of the code</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LanguageEnum
        {
            /// <summary>
            /// Enum PYTHON for value: PYTHON
            /// </summary>
            [EnumMember(Value = "PYTHON")]
            PYTHON = 1,

            /// <summary>
            /// Enum LANGUAGEUNSPECIFIED for value: LANGUAGE_UNSPECIFIED
            /// </summary>
            [EnumMember(Value = "LANGUAGE_UNSPECIFIED")]
            LANGUAGEUNSPECIFIED = 2
        }


        /// <summary>
        /// Programming language of the code
        /// </summary>
        /// <value>Programming language of the code</value>
        [DataMember(Name = "language", EmitDefaultValue = false)]
        public LanguageEnum? Language { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ExecutableCode" /> class.
        /// </summary>
        /// <param name="language">Programming language of the code.</param>
        /// <param name="code">The code to execute.</param>
        public ExecutableCode(LanguageEnum? language = default, string code = default)
        {
            this.Language = language;
            this.Code = code;
        }

        /// <summary>
        /// The code to execute
        /// </summary>
        /// <value>The code to execute</value>
        [DataMember(Name = "code", EmitDefaultValue = false)]
        public string Code { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExecutableCode {\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
