/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// FunctionCallingConfig
    /// </summary>
    [DataContract(Name = "FunctionCallingConfig")]
    public partial class FunctionCallingConfig : IValidatableObject
    {
        /// <summary>
        /// Specifies the mode in which function calling should execute
        /// </summary>
        /// <value>Specifies the mode in which function calling should execute</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ModeEnum
        {
            /// <summary>
            /// Enum MODEUNSPECIFIED for value: MODE_UNSPECIFIED
            /// </summary>
            [EnumMember(Value = "MODE_UNSPECIFIED")]
            MODEUNSPECIFIED = 1,

            /// <summary>
            /// Enum AUTO for value: AUTO
            /// </summary>
            [EnumMember(Value = "AUTO")]
            AUTO = 2,

            /// <summary>
            /// Enum ANY for value: ANY
            /// </summary>
            [EnumMember(Value = "ANY")]
            ANY = 3,

            /// <summary>
            /// Enum NONE for value: NONE
            /// </summary>
            [EnumMember(Value = "NONE")]
            NONE = 4
        }


        /// <summary>
        /// Specifies the mode in which function calling should execute
        /// </summary>
        /// <value>Specifies the mode in which function calling should execute</value>
        [DataMember(Name = "mode", EmitDefaultValue = false)]
        public ModeEnum? Mode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FunctionCallingConfig" /> class.
        /// </summary>
        /// <param name="mode">Specifies the mode in which function calling should execute.</param>
        /// <param name="allowedFunctionNames">A set of function names that, when provided, limits the functions the model will call.</param>
        public FunctionCallingConfig(ModeEnum? mode = default, Collection<string> allowedFunctionNames = default)
        {
            this.Mode = mode;
            this.AllowedFunctionNames = allowedFunctionNames;
        }

        /// <summary>
        /// A set of function names that, when provided, limits the functions the model will call
        /// </summary>
        /// <value>A set of function names that, when provided, limits the functions the model will call</value>
        [DataMember(Name = "allowedFunctionNames", EmitDefaultValue = false)]
        public Collection<string> AllowedFunctionNames { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FunctionCallingConfig {\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("  AllowedFunctionNames: ").Append(AllowedFunctionNames).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
