/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// ResponseContentPart
    /// </summary>
    [DataContract(Name = "ResponseContentPart")]
    public partial class ResponseContentPart : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseContentPart" /> class.
        /// </summary>
        /// <param name="text">Inline text.</param>
        /// <param name="functionCall">functionCall.</param>
        /// <param name="executableCode">executableCode.</param>
        /// <param name="codeExecutionResult">codeExecutionResult.</param>
        public ResponseContentPart(string text = default, FunctionCall functionCall = default, ExecutableCode executableCode = default, CodeExecutionResult codeExecutionResult = default)
        {
            this.Text = text;
            this.FunctionCall = functionCall;
            this.ExecutableCode = executableCode;
            this.CodeExecutionResult = codeExecutionResult;
        }

        /// <summary>
        /// Inline text
        /// </summary>
        /// <value>Inline text</value>
        [DataMember(Name = "text", EmitDefaultValue = false)]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets FunctionCall
        /// </summary>
        [DataMember(Name = "functionCall", EmitDefaultValue = false)]
        public FunctionCall FunctionCall { get; set; }

        /// <summary>
        /// Gets or Sets ExecutableCode
        /// </summary>
        [DataMember(Name = "executableCode", EmitDefaultValue = false)]
        public ExecutableCode ExecutableCode { get; set; }

        /// <summary>
        /// Gets or Sets CodeExecutionResult
        /// </summary>
        [DataMember(Name = "codeExecutionResult", EmitDefaultValue = false)]
        public CodeExecutionResult CodeExecutionResult { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResponseContentPart {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  FunctionCall: ").Append(FunctionCall).Append("\n");
            sb.Append("  ExecutableCode: ").Append(ExecutableCode).Append("\n");
            sb.Append("  CodeExecutionResult: ").Append(CodeExecutionResult).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
