/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// TuningExample
    /// </summary>
    [DataContract(Name = "TuningExample")]
    public partial class TuningExample : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TuningExample" /> class.
        /// </summary>
        /// <param name="textInput">Optional. Text model input.</param>
        /// <param name="output">Required. The expected model output.</param>
        public TuningExample(string textInput = default, string output = default)
        {
            this.TextInput = textInput;
            this.Output = output;
        }

        /// <summary>
        /// Optional. Text model input
        /// </summary>
        /// <value>Optional. Text model input</value>
        [DataMember(Name = "textInput", EmitDefaultValue = false)]
        public string TextInput { get; set; }

        /// <summary>
        /// Required. The expected model output
        /// </summary>
        /// <value>Required. The expected model output</value>
        [DataMember(Name = "output", EmitDefaultValue = false)]
        public string Output { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TuningExample {\n");
            sb.Append("  TextInput: ").Append(TextInput).Append("\n");
            sb.Append("  Output: ").Append(Output).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
