/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// VideoMetadata
    /// </summary>
    [DataContract(Name = "VideoMetadata")]
    public partial class VideoMetadata : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VideoMetadata" /> class.
        /// </summary>
        /// <param name="startOffset">Start offset of the video segment.</param>
        /// <param name="endOffset">End offset of the video segment.</param>
        public VideoMetadata(string startOffset = default, string endOffset = default)
        {
            this.StartOffset = startOffset;
            this.EndOffset = endOffset;
        }

        /// <summary>
        /// Start offset of the video segment
        /// </summary>
        /// <value>Start offset of the video segment</value>
        [DataMember(Name = "startOffset", EmitDefaultValue = false)]
        public string StartOffset { get; set; }

        /// <summary>
        /// End offset of the video segment
        /// </summary>
        /// <value>End offset of the video segment</value>
        [DataMember(Name = "endOffset", EmitDefaultValue = false)]
        public string EndOffset { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VideoMetadata {\n");
            sb.Append("  StartOffset: ").Append(StartOffset).Append("\n");
            sb.Append("  EndOffset: ").Append(EndOffset).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
