/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// CandidateLogprobs
    /// </summary>
    [DataContract(Name = "CandidateLogprobs")]
    public partial class CandidateLogprobs : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CandidateLogprobs" /> class.
        /// </summary>
        /// <param name="token">The candidate&#39;s token string value.</param>
        /// <param name="tokenId">The candidate&#39;s token id value.</param>
        /// <param name="logProbability">The candidate&#39;s log probability.</param>
        public CandidateLogprobs(string token = default, int tokenId = default, float logProbability = default)
        {
            this.Token = token;
            this.TokenId = tokenId;
            this.LogProbability = logProbability;
        }

        /// <summary>
        /// The candidate&#39;s token string value
        /// </summary>
        /// <value>The candidate&#39;s token string value</value>
        [DataMember(Name = "token", EmitDefaultValue = false)]
        public string Token { get; set; }

        /// <summary>
        /// The candidate&#39;s token id value
        /// </summary>
        /// <value>The candidate&#39;s token id value</value>
        [DataMember(Name = "tokenId", EmitDefaultValue = false)]
        public int TokenId { get; set; }

        /// <summary>
        /// The candidate&#39;s log probability
        /// </summary>
        /// <value>The candidate&#39;s log probability</value>
        [DataMember(Name = "logProbability", EmitDefaultValue = false)]
        public float LogProbability { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CandidateLogprobs {\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  TokenId: ").Append(TokenId).Append("\n");
            sb.Append("  LogProbability: ").Append(LogProbability).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
