/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// CustomMetadata
    /// </summary>
    [DataContract(Name = "CustomMetadata")]
    public partial class CustomMetadata : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomMetadata" /> class.
        /// </summary>
        /// <param name="key">Required. The key of the metadata to store.</param>
        /// <param name="stringValue">The string value of the metadata to store.</param>
        /// <param name="stringListValue">stringListValue.</param>
        /// <param name="numericValue">The numeric value of the metadata to store.</param>
        public CustomMetadata(string key = default, string stringValue = default, StringList stringListValue = default, float numericValue = default)
        {
            this.Key = key;
            this.StringValue = stringValue;
            this.StringListValue = stringListValue;
            this.NumericValue = numericValue;
        }

        /// <summary>
        /// Required. The key of the metadata to store
        /// </summary>
        /// <value>Required. The key of the metadata to store</value>
        [DataMember(Name = "key", EmitDefaultValue = false)]
        public string Key { get; set; }

        /// <summary>
        /// The string value of the metadata to store
        /// </summary>
        /// <value>The string value of the metadata to store</value>
        [DataMember(Name = "stringValue", EmitDefaultValue = false)]
        public string StringValue { get; set; }

        /// <summary>
        /// Gets or Sets StringListValue
        /// </summary>
        [DataMember(Name = "stringListValue", EmitDefaultValue = false)]
        public StringList StringListValue { get; set; }

        /// <summary>
        /// The numeric value of the metadata to store
        /// </summary>
        /// <value>The numeric value of the metadata to store</value>
        [DataMember(Name = "numericValue", EmitDefaultValue = false)]
        public float NumericValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomMetadata {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  StringValue: ").Append(StringValue).Append("\n");
            sb.Append("  StringListValue: ").Append(StringListValue).Append("\n");
            sb.Append("  NumericValue: ").Append(NumericValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
