/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// GeneratedImage
    /// </summary>
    [DataContract(Name = "GeneratedImage")]
    public partial class GeneratedImage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GeneratedImage" /> class.
        /// </summary>
        /// <param name="bytesBase64Encoded">Image bytes encoded in base64.</param>
        /// <param name="imageMimeType">MIME type of the image (e.g., image/jpeg, image/png).</param>
        /// <param name="gcsUri">Google Cloud Storage URI where the image is stored.</param>
        public GeneratedImage(byte[] bytesBase64Encoded = default, string imageMimeType = default, string gcsUri = default)
        {
            this.BytesBase64Encoded = bytesBase64Encoded;
            this.ImageMimeType = imageMimeType;
            this.GcsUri = gcsUri;
        }

        /// <summary>
        /// Image bytes encoded in base64
        /// </summary>
        /// <value>Image bytes encoded in base64</value>
        [DataMember(Name = "bytesBase64Encoded", EmitDefaultValue = false)]
        public byte[] BytesBase64Encoded { get; set; }

        /// <summary>
        /// MIME type of the image (e.g., image/jpeg, image/png)
        /// </summary>
        /// <value>MIME type of the image (e.g., image/jpeg, image/png)</value>
        [DataMember(Name = "imageMimeType", EmitDefaultValue = false)]
        public string ImageMimeType { get; set; }

        /// <summary>
        /// Google Cloud Storage URI where the image is stored
        /// </summary>
        /// <value>Google Cloud Storage URI where the image is stored</value>
        [DataMember(Name = "gcsUri", EmitDefaultValue = false)]
        public string GcsUri { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GeneratedImage {\n");
            sb.Append("  BytesBase64Encoded: ").Append(BytesBase64Encoded).Append("\n");
            sb.Append("  ImageMimeType: ").Append(ImageMimeType).Append("\n");
            sb.Append("  GcsUri: ").Append(GcsUri).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
