/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// GenerateContentResponse
    /// </summary>
    [DataContract(Name = "GenerateContentResponse")]
    public partial class GenerateContentResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GenerateContentResponse" /> class.
        /// </summary>
        /// <param name="candidates">candidates.</param>
        /// <param name="promptFeedback">promptFeedback.</param>
        /// <param name="usageMetadata">usageMetadata.</param>
        public GenerateContentResponse(Collection<Candidate> candidates = default, PromptFeedback promptFeedback = default, UsageMetadata usageMetadata = default)
        {
            this.Candidates = candidates;
            this.PromptFeedback = promptFeedback;
            this.UsageMetadata = usageMetadata;
        }

        /// <summary>
        /// Gets or Sets Candidates
        /// </summary>
        [DataMember(Name = "candidates", EmitDefaultValue = false)]
        public Collection<Candidate> Candidates { get; set; }

        /// <summary>
        /// Gets or Sets PromptFeedback
        /// </summary>
        [DataMember(Name = "promptFeedback", EmitDefaultValue = false)]
        public PromptFeedback PromptFeedback { get; set; }

        /// <summary>
        /// Gets or Sets UsageMetadata
        /// </summary>
        [DataMember(Name = "usageMetadata", EmitDefaultValue = false)]
        public UsageMetadata UsageMetadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GenerateContentResponse {\n");
            sb.Append("  Candidates: ").Append(Candidates).Append("\n");
            sb.Append("  PromptFeedback: ").Append(PromptFeedback).Append("\n");
            sb.Append("  UsageMetadata: ").Append(UsageMetadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
