/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// GroundingPassageId
    /// </summary>
    [DataContract(Name = "GroundingPassageId")]
    public partial class GroundingPassageId : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GroundingPassageId" /> class.
        /// </summary>
        /// <param name="passageId">ID of the passage matching the GenerateAnswerRequest&#39;s GroundingPassage.id.</param>
        /// <param name="partIndex">Index of the part within the GenerateAnswerRequest&#39;s GroundingPassage.content parts list.</param>
        public GroundingPassageId(string passageId = default, int partIndex = default)
        {
            this.PassageId = passageId;
            this.PartIndex = partIndex;
        }

        /// <summary>
        /// ID of the passage matching the GenerateAnswerRequest&#39;s GroundingPassage.id
        /// </summary>
        /// <value>ID of the passage matching the GenerateAnswerRequest&#39;s GroundingPassage.id</value>
        [DataMember(Name = "passageId", EmitDefaultValue = false)]
        public string PassageId { get; set; }

        /// <summary>
        /// Index of the part within the GenerateAnswerRequest&#39;s GroundingPassage.content parts list
        /// </summary>
        /// <value>Index of the part within the GenerateAnswerRequest&#39;s GroundingPassage.content parts list</value>
        [DataMember(Name = "partIndex", EmitDefaultValue = false)]
        public int PartIndex { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GroundingPassageId {\n");
            sb.Append("  PassageId: ").Append(PassageId).Append("\n");
            sb.Append("  PartIndex: ").Append(PartIndex).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
