/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// LogprobsResult
    /// </summary>
    [DataContract(Name = "LogprobsResult")]
    public partial class LogprobsResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LogprobsResult" /> class.
        /// </summary>
        /// <param name="topCandidates">Length &#x3D; total number of decoding steps.</param>
        /// <param name="chosenCandidates">Length &#x3D; total number of decoding steps.</param>
        public LogprobsResult(Collection<TopCandidates> topCandidates = default, Collection<Candidate> chosenCandidates = default)
        {
            this.TopCandidates = topCandidates;
            this.ChosenCandidates = chosenCandidates;
        }

        /// <summary>
        /// Length &#x3D; total number of decoding steps
        /// </summary>
        /// <value>Length &#x3D; total number of decoding steps</value>
        [DataMember(Name = "topCandidates", EmitDefaultValue = false)]
        public Collection<TopCandidates> TopCandidates { get; set; }

        /// <summary>
        /// Length &#x3D; total number of decoding steps
        /// </summary>
        /// <value>Length &#x3D; total number of decoding steps</value>
        [DataMember(Name = "chosenCandidates", EmitDefaultValue = false)]
        public Collection<Candidate> ChosenCandidates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LogprobsResult {\n");
            sb.Append("  TopCandidates: ").Append(TopCandidates).Append("\n");
            sb.Append("  ChosenCandidates: ").Append(ChosenCandidates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
