/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// QueryCorpusRequest
    /// </summary>
    [DataContract(Name = "QueryCorpusRequest")]
    public partial class QueryCorpusRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryCorpusRequest" /> class.
        /// </summary>
        /// <param name="query">Required. Query string to perform semantic search.</param>
        /// <param name="metadataFilters">Optional. Filter for Chunk and Document custom metadata.</param>
        /// <param name="resultsCount">Optional. The maximum number of Chunks to return.</param>
        public QueryCorpusRequest(string query = default, Collection<MetadataFilter> metadataFilters = default, int resultsCount = default)
        {
            this.Query = query;
            this.MetadataFilters = metadataFilters;
            this.ResultsCount = resultsCount;
        }

        /// <summary>
        /// Required. Query string to perform semantic search
        /// </summary>
        /// <value>Required. Query string to perform semantic search</value>
        [DataMember(Name = "query", EmitDefaultValue = false)]
        public string Query { get; set; }

        /// <summary>
        /// Optional. Filter for Chunk and Document custom metadata
        /// </summary>
        /// <value>Optional. Filter for Chunk and Document custom metadata</value>
        [DataMember(Name = "metadataFilters", EmitDefaultValue = false)]
        public Collection<MetadataFilter> MetadataFilters { get; set; }

        /// <summary>
        /// Optional. The maximum number of Chunks to return
        /// </summary>
        /// <value>Optional. The maximum number of Chunks to return</value>
        [DataMember(Name = "resultsCount", EmitDefaultValue = false)]
        public int ResultsCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryCorpusRequest {\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("  MetadataFilters: ").Append(MetadataFilters).Append("\n");
            sb.Append("  ResultsCount: ").Append(ResultsCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
