/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// RelevantChunk
    /// </summary>
    [DataContract(Name = "RelevantChunk")]
    public partial class RelevantChunk : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RelevantChunk" /> class.
        /// </summary>
        /// <param name="chunkRelevanceScore">Chunk relevance to the query.</param>
        /// <param name="chunk">chunk.</param>
        public RelevantChunk(float chunkRelevanceScore = default, Chunk chunk = default)
        {
            this.ChunkRelevanceScore = chunkRelevanceScore;
            this.Chunk = chunk;
        }

        /// <summary>
        /// Chunk relevance to the query
        /// </summary>
        /// <value>Chunk relevance to the query</value>
        [DataMember(Name = "chunkRelevanceScore", EmitDefaultValue = false)]
        public float ChunkRelevanceScore { get; set; }

        /// <summary>
        /// Gets or Sets Chunk
        /// </summary>
        [DataMember(Name = "chunk", EmitDefaultValue = false)]
        public Chunk Chunk { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RelevantChunk {\n");
            sb.Append("  ChunkRelevanceScore: ").Append(ChunkRelevanceScore).Append("\n");
            sb.Append("  Chunk: ").Append(Chunk).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
