/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GeminiSharp.Client.FileParameter;
using OpenAPIDateConverter = GeminiSharp.Client.OpenAPIDateConverter;

namespace GeminiSharp.Model
{
    /// <summary>
    /// SemanticRetrieverChunk
    /// </summary>
    [DataContract(Name = "SemanticRetrieverChunk")]
    public partial class SemanticRetrieverChunk : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SemanticRetrieverChunk" /> class.
        /// </summary>
        /// <param name="source">Name of the source matching the request&#39;s SemanticRetrieverConfig.source.</param>
        /// <param name="chunk">Name of the Chunk containing the attributed text.</param>
        public SemanticRetrieverChunk(string source = default, string chunk = default)
        {
            this.Source = source;
            this.Chunk = chunk;
        }

        /// <summary>
        /// Name of the source matching the request&#39;s SemanticRetrieverConfig.source
        /// </summary>
        /// <value>Name of the source matching the request&#39;s SemanticRetrieverConfig.source</value>
        [DataMember(Name = "source", EmitDefaultValue = false)]
        public string Source { get; set; }

        /// <summary>
        /// Name of the Chunk containing the attributed text
        /// </summary>
        /// <value>Name of the Chunk containing the attributed text</value>
        [DataMember(Name = "chunk", EmitDefaultValue = false)]
        public string Chunk { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SemanticRetrieverChunk {\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  Chunk: ").Append(Chunk).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
