/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing ApiErrorResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiErrorResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiErrorResponse
        //private ApiErrorResponse instance;

        public ApiErrorResponseTests()
        {
            // TODO uncomment below to create an instance of ApiErrorResponse
            //instance = new ApiErrorResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiErrorResponse
        /// </summary>
        [Fact]
        public void ApiErrorResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiErrorResponse
            //Assert.IsType<ApiErrorResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
