/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing BatchEmbedContents200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchEmbedContents200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchEmbedContents200Response
        //private BatchEmbedContents200Response instance;

        public BatchEmbedContents200ResponseTests()
        {
            // TODO uncomment below to create an instance of BatchEmbedContents200Response
            //instance = new BatchEmbedContents200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchEmbedContents200Response
        /// </summary>
        [Fact]
        public void BatchEmbedContents200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchEmbedContents200Response
            //Assert.IsType<BatchEmbedContents200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Embeddings'
        /// </summary>
        [Fact]
        public void EmbeddingsTest()
        {
            // TODO unit test for the property 'Embeddings'
        }
    }
}
