/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing ChunkData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChunkDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChunkData
        //private ChunkData instance;

        public ChunkDataTests()
        {
            // TODO uncomment below to create an instance of ChunkData
            //instance = new ChunkData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChunkData
        /// </summary>
        [Fact]
        public void ChunkDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChunkData
            //Assert.IsType<ChunkData>(instance);
        }

        /// <summary>
        /// Test the property 'StringValue'
        /// </summary>
        [Fact]
        public void StringValueTest()
        {
            // TODO unit test for the property 'StringValue'
        }
    }
}
