/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing File
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for File
        //private File instance;

        public FileTests()
        {
            // TODO uncomment below to create an instance of File
            //instance = new File();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of File
        /// </summary>
        [Fact]
        public void FileInstanceTest()
        {
            // TODO uncomment below to test "IsType" File
            //Assert.IsType<File>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Fact]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }

        /// <summary>
        /// Test the property 'SizeBytes'
        /// </summary>
        [Fact]
        public void SizeBytesTest()
        {
            // TODO unit test for the property 'SizeBytes'
        }

        /// <summary>
        /// Test the property 'CreateTime'
        /// </summary>
        [Fact]
        public void CreateTimeTest()
        {
            // TODO unit test for the property 'CreateTime'
        }

        /// <summary>
        /// Test the property 'UpdateTime'
        /// </summary>
        [Fact]
        public void UpdateTimeTest()
        {
            // TODO unit test for the property 'UpdateTime'
        }

        /// <summary>
        /// Test the property 'ExpirationTime'
        /// </summary>
        [Fact]
        public void ExpirationTimeTest()
        {
            // TODO unit test for the property 'ExpirationTime'
        }

        /// <summary>
        /// Test the property 'Sha256Hash'
        /// </summary>
        [Fact]
        public void Sha256HashTest()
        {
            // TODO unit test for the property 'Sha256Hash'
        }

        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'VideoMetadata'
        /// </summary>
        [Fact]
        public void VideoMetadataTest()
        {
            // TODO unit test for the property 'VideoMetadata'
        }
    }
}
