/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing FileData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FileData
        //private FileData instance;

        public FileDataTests()
        {
            // TODO uncomment below to create an instance of FileData
            //instance = new FileData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FileData
        /// </summary>
        [Fact]
        public void FileDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" FileData
            //Assert.IsType<FileData>(instance);
        }

        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Fact]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }

        /// <summary>
        /// Test the property 'FileUri'
        /// </summary>
        [Fact]
        public void FileUriTest()
        {
            // TODO unit test for the property 'FileUri'
        }
    }
}
