/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing GenerateImageRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerateImageRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenerateImageRequest
        //private GenerateImageRequest instance;

        public GenerateImageRequestTests()
        {
            // TODO uncomment below to create an instance of GenerateImageRequest
            //instance = new GenerateImageRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenerateImageRequest
        /// </summary>
        [Fact]
        public void GenerateImageRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GenerateImageRequest
            //Assert.IsType<GenerateImageRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Fact]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }

        /// <summary>
        /// Test the property 'NumberOfImages'
        /// </summary>
        [Fact]
        public void NumberOfImagesTest()
        {
            // TODO unit test for the property 'NumberOfImages'
        }

        /// <summary>
        /// Test the property 'AspectRatio'
        /// </summary>
        [Fact]
        public void AspectRatioTest()
        {
            // TODO unit test for the property 'AspectRatio'
        }

        /// <summary>
        /// Test the property 'NegativePrompt'
        /// </summary>
        [Fact]
        public void NegativePromptTest()
        {
            // TODO unit test for the property 'NegativePrompt'
        }

        /// <summary>
        /// Test the property 'SafetyFilterLevel'
        /// </summary>
        [Fact]
        public void SafetyFilterLevelTest()
        {
            // TODO unit test for the property 'SafetyFilterLevel'
        }

        /// <summary>
        /// Test the property 'PersonGeneration'
        /// </summary>
        [Fact]
        public void PersonGenerationTest()
        {
            // TODO unit test for the property 'PersonGeneration'
        }
    }
}
