/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing RetrievalMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RetrievalMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RetrievalMetadata
        //private RetrievalMetadata instance;

        public RetrievalMetadataTests()
        {
            // TODO uncomment below to create an instance of RetrievalMetadata
            //instance = new RetrievalMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RetrievalMetadata
        /// </summary>
        [Fact]
        public void RetrievalMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" RetrievalMetadata
            //Assert.IsType<RetrievalMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'GoogleSearchDynamicRetrievalScore'
        /// </summary>
        [Fact]
        public void GoogleSearchDynamicRetrievalScoreTest()
        {
            // TODO unit test for the property 'GoogleSearchDynamicRetrievalScore'
        }
    }
}
