/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing CachedContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CachedContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CachedContent
        //private CachedContent instance;

        public CachedContentTests()
        {
            // TODO uncomment below to create an instance of CachedContent
            //instance = new CachedContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CachedContent
        /// </summary>
        [Fact]
        public void CachedContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" CachedContent
            //Assert.IsType<CachedContent>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

        /// <summary>
        /// Test the property 'SystemInstruction'
        /// </summary>
        [Fact]
        public void SystemInstructionTest()
        {
            // TODO unit test for the property 'SystemInstruction'
        }

        /// <summary>
        /// Test the property 'Contents'
        /// </summary>
        [Fact]
        public void ContentsTest()
        {
            // TODO unit test for the property 'Contents'
        }

        /// <summary>
        /// Test the property 'Tools'
        /// </summary>
        [Fact]
        public void ToolsTest()
        {
            // TODO unit test for the property 'Tools'
        }

        /// <summary>
        /// Test the property 'ToolConfig'
        /// </summary>
        [Fact]
        public void ToolConfigTest()
        {
            // TODO unit test for the property 'ToolConfig'
        }

        /// <summary>
        /// Test the property 'CreateTime'
        /// </summary>
        [Fact]
        public void CreateTimeTest()
        {
            // TODO unit test for the property 'CreateTime'
        }

        /// <summary>
        /// Test the property 'UpdateTime'
        /// </summary>
        [Fact]
        public void UpdateTimeTest()
        {
            // TODO unit test for the property 'UpdateTime'
        }

        /// <summary>
        /// Test the property 'UsageMetadata'
        /// </summary>
        [Fact]
        public void UsageMetadataTest()
        {
            // TODO unit test for the property 'UsageMetadata'
        }

        /// <summary>
        /// Test the property 'ExpireTime'
        /// </summary>
        [Fact]
        public void ExpireTimeTest()
        {
            // TODO unit test for the property 'ExpireTime'
        }

        /// <summary>
        /// Test the property 'Ttl'
        /// </summary>
        [Fact]
        public void TtlTest()
        {
            // TODO unit test for the property 'Ttl'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
    }
}
