/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing CachedContentUsageMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CachedContentUsageMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CachedContentUsageMetadata
        //private CachedContentUsageMetadata instance;

        public CachedContentUsageMetadataTests()
        {
            // TODO uncomment below to create an instance of CachedContentUsageMetadata
            //instance = new CachedContentUsageMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CachedContentUsageMetadata
        /// </summary>
        [Fact]
        public void CachedContentUsageMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CachedContentUsageMetadata
            //Assert.IsType<CachedContentUsageMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'TotalTokenCount'
        /// </summary>
        [Fact]
        public void TotalTokenCountTest()
        {
            // TODO unit test for the property 'TotalTokenCount'
        }
    }
}
