/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing CreateTunedModelRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateTunedModelRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateTunedModelRequest
        //private CreateTunedModelRequest instance;

        public CreateTunedModelRequestTests()
        {
            // TODO uncomment below to create an instance of CreateTunedModelRequest
            //instance = new CreateTunedModelRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateTunedModelRequest
        /// </summary>
        [Fact]
        public void CreateTunedModelRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateTunedModelRequest
            //Assert.IsType<CreateTunedModelRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TunedModelId'
        /// </summary>
        [Fact]
        public void TunedModelIdTest()
        {
            // TODO unit test for the property 'TunedModelId'
        }

        /// <summary>
        /// Test the property 'TunedModel'
        /// </summary>
        [Fact]
        public void TunedModelTest()
        {
            // TODO unit test for the property 'TunedModel'
        }
    }
}
