/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing CustomMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomMetadata
        //private CustomMetadata instance;

        public CustomMetadataTests()
        {
            // TODO uncomment below to create an instance of CustomMetadata
            //instance = new CustomMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomMetadata
        /// </summary>
        [Fact]
        public void CustomMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomMetadata
            //Assert.IsType<CustomMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'StringValue'
        /// </summary>
        [Fact]
        public void StringValueTest()
        {
            // TODO unit test for the property 'StringValue'
        }

        /// <summary>
        /// Test the property 'StringListValue'
        /// </summary>
        [Fact]
        public void StringListValueTest()
        {
            // TODO unit test for the property 'StringListValue'
        }

        /// <summary>
        /// Test the property 'NumericValue'
        /// </summary>
        [Fact]
        public void NumericValueTest()
        {
            // TODO unit test for the property 'NumericValue'
        }
    }
}
