/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing FunctionCallingConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FunctionCallingConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FunctionCallingConfig
        //private FunctionCallingConfig instance;

        public FunctionCallingConfigTests()
        {
            // TODO uncomment below to create an instance of FunctionCallingConfig
            //instance = new FunctionCallingConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FunctionCallingConfig
        /// </summary>
        [Fact]
        public void FunctionCallingConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" FunctionCallingConfig
            //Assert.IsType<FunctionCallingConfig>(instance);
        }

        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }

        /// <summary>
        /// Test the property 'AllowedFunctionNames'
        /// </summary>
        [Fact]
        public void AllowedFunctionNamesTest()
        {
            // TODO unit test for the property 'AllowedFunctionNames'
        }
    }
}
