/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing GeminiModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeminiModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeminiModel
        //private GeminiModel instance;

        public GeminiModelTests()
        {
            // TODO uncomment below to create an instance of GeminiModel
            //instance = new GeminiModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeminiModel
        /// </summary>
        [Fact]
        public void GeminiModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" GeminiModel
            //Assert.IsType<GeminiModel>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'BaseModelId'
        /// </summary>
        [Fact]
        public void BaseModelIdTest()
        {
            // TODO unit test for the property 'BaseModelId'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'InputTokenLimit'
        /// </summary>
        [Fact]
        public void InputTokenLimitTest()
        {
            // TODO unit test for the property 'InputTokenLimit'
        }

        /// <summary>
        /// Test the property 'OutputTokenLimit'
        /// </summary>
        [Fact]
        public void OutputTokenLimitTest()
        {
            // TODO unit test for the property 'OutputTokenLimit'
        }

        /// <summary>
        /// Test the property 'SupportedGenerationMethods'
        /// </summary>
        [Fact]
        public void SupportedGenerationMethodsTest()
        {
            // TODO unit test for the property 'SupportedGenerationMethods'
        }

        /// <summary>
        /// Test the property 'Temperature'
        /// </summary>
        [Fact]
        public void TemperatureTest()
        {
            // TODO unit test for the property 'Temperature'
        }

        /// <summary>
        /// Test the property 'MaxTemperature'
        /// </summary>
        [Fact]
        public void MaxTemperatureTest()
        {
            // TODO unit test for the property 'MaxTemperature'
        }

        /// <summary>
        /// Test the property 'TopP'
        /// </summary>
        [Fact]
        public void TopPTest()
        {
            // TODO unit test for the property 'TopP'
        }

        /// <summary>
        /// Test the property 'TopK'
        /// </summary>
        [Fact]
        public void TopKTest()
        {
            // TODO unit test for the property 'TopK'
        }
    }
}
