/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing GeneratedImage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeneratedImageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeneratedImage
        //private GeneratedImage instance;

        public GeneratedImageTests()
        {
            // TODO uncomment below to create an instance of GeneratedImage
            //instance = new GeneratedImage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeneratedImage
        /// </summary>
        [Fact]
        public void GeneratedImageInstanceTest()
        {
            // TODO uncomment below to test "IsType" GeneratedImage
            //Assert.IsType<GeneratedImage>(instance);
        }

        /// <summary>
        /// Test the property 'BytesBase64Encoded'
        /// </summary>
        [Fact]
        public void BytesBase64EncodedTest()
        {
            // TODO unit test for the property 'BytesBase64Encoded'
        }

        /// <summary>
        /// Test the property 'ImageMimeType'
        /// </summary>
        [Fact]
        public void ImageMimeTypeTest()
        {
            // TODO unit test for the property 'ImageMimeType'
        }

        /// <summary>
        /// Test the property 'GcsUri'
        /// </summary>
        [Fact]
        public void GcsUriTest()
        {
            // TODO unit test for the property 'GcsUri'
        }
    }
}
