/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing GenerateContentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerateContentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenerateContentResponse
        //private GenerateContentResponse instance;

        public GenerateContentResponseTests()
        {
            // TODO uncomment below to create an instance of GenerateContentResponse
            //instance = new GenerateContentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenerateContentResponse
        /// </summary>
        [Fact]
        public void GenerateContentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GenerateContentResponse
            //Assert.IsType<GenerateContentResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Candidates'
        /// </summary>
        [Fact]
        public void CandidatesTest()
        {
            // TODO unit test for the property 'Candidates'
        }

        /// <summary>
        /// Test the property 'PromptFeedback'
        /// </summary>
        [Fact]
        public void PromptFeedbackTest()
        {
            // TODO unit test for the property 'PromptFeedback'
        }

        /// <summary>
        /// Test the property 'UsageMetadata'
        /// </summary>
        [Fact]
        public void UsageMetadataTest()
        {
            // TODO unit test for the property 'UsageMetadata'
        }
    }
}
