/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing GenerateContentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerateContentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenerateContentRequest
        //private GenerateContentRequest instance;

        public GenerateContentRequestTests()
        {
            // TODO uncomment below to create an instance of GenerateContentRequest
            //instance = new GenerateContentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenerateContentRequest
        /// </summary>
        [Fact]
        public void GenerateContentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GenerateContentRequest
            //Assert.IsType<GenerateContentRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Contents'
        /// </summary>
        [Fact]
        public void ContentsTest()
        {
            // TODO unit test for the property 'Contents'
        }

        /// <summary>
        /// Test the property 'Tools'
        /// </summary>
        [Fact]
        public void ToolsTest()
        {
            // TODO unit test for the property 'Tools'
        }

        /// <summary>
        /// Test the property 'ToolConfig'
        /// </summary>
        [Fact]
        public void ToolConfigTest()
        {
            // TODO unit test for the property 'ToolConfig'
        }

        /// <summary>
        /// Test the property 'SafetySettings'
        /// </summary>
        [Fact]
        public void SafetySettingsTest()
        {
            // TODO unit test for the property 'SafetySettings'
        }

        /// <summary>
        /// Test the property 'SystemInstruction'
        /// </summary>
        [Fact]
        public void SystemInstructionTest()
        {
            // TODO unit test for the property 'SystemInstruction'
        }

        /// <summary>
        /// Test the property 'GenerationConfig'
        /// </summary>
        [Fact]
        public void GenerationConfigTest()
        {
            // TODO unit test for the property 'GenerationConfig'
        }

        /// <summary>
        /// Test the property 'CachedContent'
        /// </summary>
        [Fact]
        public void CachedContentTest()
        {
            // TODO unit test for the property 'CachedContent'
        }
    }
}
