/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing GroundingMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroundingMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GroundingMetadata
        //private GroundingMetadata instance;

        public GroundingMetadataTests()
        {
            // TODO uncomment below to create an instance of GroundingMetadata
            //instance = new GroundingMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroundingMetadata
        /// </summary>
        [Fact]
        public void GroundingMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" GroundingMetadata
            //Assert.IsType<GroundingMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'GroundingChunks'
        /// </summary>
        [Fact]
        public void GroundingChunksTest()
        {
            // TODO unit test for the property 'GroundingChunks'
        }

        /// <summary>
        /// Test the property 'GroundingSupports'
        /// </summary>
        [Fact]
        public void GroundingSupportsTest()
        {
            // TODO unit test for the property 'GroundingSupports'
        }

        /// <summary>
        /// Test the property 'WebSearchQueries'
        /// </summary>
        [Fact]
        public void WebSearchQueriesTest()
        {
            // TODO unit test for the property 'WebSearchQueries'
        }

        /// <summary>
        /// Test the property 'SearchEntryPoint'
        /// </summary>
        [Fact]
        public void SearchEntryPointTest()
        {
            // TODO unit test for the property 'SearchEntryPoint'
        }

        /// <summary>
        /// Test the property 'RetrievalMetadata'
        /// </summary>
        [Fact]
        public void RetrievalMetadataTest()
        {
            // TODO unit test for the property 'RetrievalMetadata'
        }
    }
}
