/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing GroundingSupport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroundingSupportTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GroundingSupport
        //private GroundingSupport instance;

        public GroundingSupportTests()
        {
            // TODO uncomment below to create an instance of GroundingSupport
            //instance = new GroundingSupport();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroundingSupport
        /// </summary>
        [Fact]
        public void GroundingSupportInstanceTest()
        {
            // TODO uncomment below to test "IsType" GroundingSupport
            //Assert.IsType<GroundingSupport>(instance);
        }

        /// <summary>
        /// Test the property 'Segment'
        /// </summary>
        [Fact]
        public void SegmentTest()
        {
            // TODO unit test for the property 'Segment'
        }

        /// <summary>
        /// Test the property 'GroundingChunkIndices'
        /// </summary>
        [Fact]
        public void GroundingChunkIndicesTest()
        {
            // TODO unit test for the property 'GroundingChunkIndices'
        }

        /// <summary>
        /// Test the property 'ConfidenceScores'
        /// </summary>
        [Fact]
        public void ConfidenceScoresTest()
        {
            // TODO unit test for the property 'ConfidenceScores'
        }
    }
}
