/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing RelevantChunk
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RelevantChunkTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RelevantChunk
        //private RelevantChunk instance;

        public RelevantChunkTests()
        {
            // TODO uncomment below to create an instance of RelevantChunk
            //instance = new RelevantChunk();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RelevantChunk
        /// </summary>
        [Fact]
        public void RelevantChunkInstanceTest()
        {
            // TODO uncomment below to test "IsType" RelevantChunk
            //Assert.IsType<RelevantChunk>(instance);
        }

        /// <summary>
        /// Test the property 'ChunkRelevanceScore'
        /// </summary>
        [Fact]
        public void ChunkRelevanceScoreTest()
        {
            // TODO unit test for the property 'ChunkRelevanceScore'
        }

        /// <summary>
        /// Test the property 'Chunk'
        /// </summary>
        [Fact]
        public void ChunkTest()
        {
            // TODO unit test for the property 'Chunk'
        }
    }
}
