/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing RequestContentPart
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestContentPartTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestContentPart
        //private RequestContentPart instance;

        public RequestContentPartTests()
        {
            // TODO uncomment below to create an instance of RequestContentPart
            //instance = new RequestContentPart();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestContentPart
        /// </summary>
        [Fact]
        public void RequestContentPartInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestContentPart
            //Assert.IsType<RequestContentPart>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'InlineData'
        /// </summary>
        [Fact]
        public void InlineDataTest()
        {
            // TODO unit test for the property 'InlineData'
        }

        /// <summary>
        /// Test the property 'FileData'
        /// </summary>
        [Fact]
        public void FileDataTest()
        {
            // TODO unit test for the property 'FileData'
        }

        /// <summary>
        /// Test the property 'FunctionCall'
        /// </summary>
        [Fact]
        public void FunctionCallTest()
        {
            // TODO unit test for the property 'FunctionCall'
        }

        /// <summary>
        /// Test the property 'FunctionResponse'
        /// </summary>
        [Fact]
        public void FunctionResponseTest()
        {
            // TODO unit test for the property 'FunctionResponse'
        }

        /// <summary>
        /// Test the property 'ExecutableCode'
        /// </summary>
        [Fact]
        public void ExecutableCodeTest()
        {
            // TODO unit test for the property 'ExecutableCode'
        }

        /// <summary>
        /// Test the property 'CodeExecutionResult'
        /// </summary>
        [Fact]
        public void CodeExecutionResultTest()
        {
            // TODO unit test for the property 'CodeExecutionResult'
        }

        /// <summary>
        /// Test the property 'VideoMetadata'
        /// </summary>
        [Fact]
        public void VideoMetadataTest()
        {
            // TODO unit test for the property 'VideoMetadata'
        }
    }
}
