/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing ResponseContentPart
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseContentPartTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseContentPart
        //private ResponseContentPart instance;

        public ResponseContentPartTests()
        {
            // TODO uncomment below to create an instance of ResponseContentPart
            //instance = new ResponseContentPart();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseContentPart
        /// </summary>
        [Fact]
        public void ResponseContentPartInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResponseContentPart
            //Assert.IsType<ResponseContentPart>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'FunctionCall'
        /// </summary>
        [Fact]
        public void FunctionCallTest()
        {
            // TODO unit test for the property 'FunctionCall'
        }

        /// <summary>
        /// Test the property 'ExecutableCode'
        /// </summary>
        [Fact]
        public void ExecutableCodeTest()
        {
            // TODO unit test for the property 'ExecutableCode'
        }

        /// <summary>
        /// Test the property 'CodeExecutionResult'
        /// </summary>
        [Fact]
        public void CodeExecutionResultTest()
        {
            // TODO unit test for the property 'CodeExecutionResult'
        }
    }
}
