/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing SafetySetting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SafetySettingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SafetySetting
        //private SafetySetting instance;

        public SafetySettingTests()
        {
            // TODO uncomment below to create an instance of SafetySetting
            //instance = new SafetySetting();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SafetySetting
        /// </summary>
        [Fact]
        public void SafetySettingInstanceTest()
        {
            // TODO uncomment below to test "IsType" SafetySetting
            //Assert.IsType<SafetySetting>(instance);
        }

        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }

        /// <summary>
        /// Test the property 'Threshold'
        /// </summary>
        [Fact]
        public void ThresholdTest()
        {
            // TODO unit test for the property 'Threshold'
        }
    }
}
