/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing TunedModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TunedModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TunedModel
        //private TunedModel instance;

        public TunedModelTests()
        {
            // TODO uncomment below to create an instance of TunedModel
            //instance = new TunedModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TunedModel
        /// </summary>
        [Fact]
        public void TunedModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" TunedModel
            //Assert.IsType<TunedModel>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'CreateTime'
        /// </summary>
        [Fact]
        public void CreateTimeTest()
        {
            // TODO unit test for the property 'CreateTime'
        }

        /// <summary>
        /// Test the property 'UpdateTime'
        /// </summary>
        [Fact]
        public void UpdateTimeTest()
        {
            // TODO unit test for the property 'UpdateTime'
        }

        /// <summary>
        /// Test the property 'TunedModelSource'
        /// </summary>
        [Fact]
        public void TunedModelSourceTest()
        {
            // TODO unit test for the property 'TunedModelSource'
        }

        /// <summary>
        /// Test the property 'BaseModel'
        /// </summary>
        [Fact]
        public void BaseModelTest()
        {
            // TODO unit test for the property 'BaseModel'
        }

        /// <summary>
        /// Test the property 'TuningTask'
        /// </summary>
        [Fact]
        public void TuningTaskTest()
        {
            // TODO unit test for the property 'TuningTask'
        }

        /// <summary>
        /// Test the property 'Temperature'
        /// </summary>
        [Fact]
        public void TemperatureTest()
        {
            // TODO unit test for the property 'Temperature'
        }

        /// <summary>
        /// Test the property 'TopP'
        /// </summary>
        [Fact]
        public void TopPTest()
        {
            // TODO unit test for the property 'TopP'
        }

        /// <summary>
        /// Test the property 'TopK'
        /// </summary>
        [Fact]
        public void TopKTest()
        {
            // TODO unit test for the property 'TopK'
        }
    }
}
