/*
 * Google Gemini API
 *
 * Comprehensive API for interacting with Google's Gemini models supporting text, chat, image generation, file uploads, grounding, code execution, model tuning, and more.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeminiSharp.Model;
using GeminiSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeminiSharp.Test.Model
{
    /// <summary>
    ///  Class for testing UsageMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UsageMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UsageMetadata
        //private UsageMetadata instance;

        public UsageMetadataTests()
        {
            // TODO uncomment below to create an instance of UsageMetadata
            //instance = new UsageMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UsageMetadata
        /// </summary>
        [Fact]
        public void UsageMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" UsageMetadata
            //Assert.IsType<UsageMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'PromptTokenCount'
        /// </summary>
        [Fact]
        public void PromptTokenCountTest()
        {
            // TODO unit test for the property 'PromptTokenCount'
        }

        /// <summary>
        /// Test the property 'CandidatesTokenCount'
        /// </summary>
        [Fact]
        public void CandidatesTokenCountTest()
        {
            // TODO unit test for the property 'CandidatesTokenCount'
        }

        /// <summary>
        /// Test the property 'TotalTokenCount'
        /// </summary>
        [Fact]
        public void TotalTokenCountTest()
        {
            // TODO unit test for the property 'TotalTokenCount'
        }

        /// <summary>
        /// Test the property 'CachedContentTokenCount'
        /// </summary>
        [Fact]
        public void CachedContentTokenCountTest()
        {
            // TODO unit test for the property 'CachedContentTokenCount'
        }
    }
}
