using System.Text.Json.Serialization;

namespace GeminiSharp.Models.Response
{
    /// <summary>
    /// Represents an individual candidate response generated by the model.
    /// </summary>
    public class Candidate
    {
        /// <summary>
        /// Gets or sets the content generated by the model.
        /// </summary>
        [JsonPropertyName("content")]
        public ResponseContent? Content { get; set; }

        /// <summary>
        /// Gets or sets the reason why the model stopped generating tokens.
        /// </summary>
        [JsonPropertyName("finishReason")]
        public string? FinishReason { get; set; }

        /// <summary>
        /// Gets or sets metadata related to citations, if available.
        /// </summary>
        [JsonPropertyName("citationMetadata")]
        public CitationMetadata? CitationMetadata { get; set; }

        /// <summary>
        /// Gets or sets the average log probabilities of the generated tokens.
        /// </summary>
        [JsonPropertyName("avgLogprobs")]
        public double? AvgLogprobs { get; set; }
    }
}