name: Manual Publish to NuGet (Dockerized)

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build & Publish using Docker
        run: |
          docker build --build-arg NUGET_API_KEY=${{ secrets.NUGET_API_KEY }} -t gemini-nuget-publisher .
          docker run --rm gemini-nuget-publisher

  log_date_and_time:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Update last deploy time
        run: |
          echo "Last deploy (IST): $(TZ=Asia/Kolkata date)" >> last_deploy.txt
          
      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"

      - name: Commit and push changes
        run: |
          git pull origin main --rebase=false
          git add last_deploy.txt
          git commit -m "Update last deploy time [skip ci]"
          git push origin main
