name: Manual Publish to NuGet (Dockerized)

on:
  workflow_dispatch:  

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build & Publish using Docker
        run: |
          docker build --build-arg NUGET_API_KEY=${{ secrets.NUGET_API_KEY }} -t gemini-nuget-publisher .
          docker run --rm gemini-nuget-publisher

      - name: Update publish log
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          echo "Published at $TIMESTAMP" >> publish_log.txt

  log_date_and_time:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update last deploy time
        run: |
          echo "Last deploy (IST): $(TZ=Asia/Kolkata date)" >> last_deploy.txt || echo "Last deploy (IST): $(TZ=Asia/Kolkata date)" > last_deploy.txt
        if: always()

      - name: Configure Git
        run: |
          git config --global user.name ${{ secrets.USERNAME}}
          git config --global user.email ${{ secrets.USER_EMAIL}}

      - name: Commit and push changes
        run: |
          git pull origin main --rebase=false
          git add last_deploy.txt
          git commit -m "Update last deploy time [skip ci]"
          git push origin main