name: Deploy GeminiSharp Docs to GitHub Pages

on:
  # Runs on pushes to the master branch
  push:
    branches: ["master"]
    # Only trigger when changes are made to the docs/ folder
    paths:
      - 'docs/**'
  workflow_dispatch:

# Permissions for deploying to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Prevent concurrent deployments, but don’t cancel in-progress runs
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload docs folder as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Only upload the docs/ folder
          path: 'docs/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Log deployment URL
        run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"
